info:
  contact: {}
  description: this is a rest api server for items
  title: Tickets API
  version: "1"
paths:
  /tickets/getAverage/:dest:
    get:
      description: Getl all tickets by country
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema: {}
      summary: Show average of tickets by country
      tags:
      - ticjets
  /tickets/getByCountry/:dest:
    get:
      description: Getl all tickets by country
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema: {}
      summary: Show All tickets by country
      tags:
      - ticjets
swagger: "2.0"
